@echo off

SET HMDRIVE=C:
SET ROOTWS=%HMDRIVE%\ROS_WS
SET PROJECT_DIR_NAME=climate_room_project_pc
SET TMP_DIR=tmp
SET SRC_DIR=src
SET PKG_MSGS=custom_msgs
SET PKG_NODES=pc_node

CD %HMDRIVE%\
IF NOT EXIST %ROOTWS% mkdir %ROOTWS%
CD %ROOTWS%
IF EXIST %PROJECT_DIR_NAME% rmdir %PROJECT_DIR_NAME%
mkdir %PROJECT_DIR_NAME%
CD %PROJECT_DIR_NAME%
mkdir %TMP_DIR%
mkdir %SRC_DIR%
CD %ROOTWS%\%PROJECT_DIR_NAME%\%TMP_DIR%
git clone https://github.com/padawan51/climate_room_project_pc.git
CD %ROOTWS%\%PROJECT_DIR_NAME%\%SRC_DIR%
catkin_init_workspace
CD %ROOTWS%\%PROJECT_DIR_NAME%
catkin_make
CD %ROOTWS%\%PROJECT_DIR_NAME%\%SRC_DIR%
catkin_create_pkg %PKG_MSGS% roscpp
rmdir /S /Q %PKG_MSGS%
xcopy %ROOTWS%\%PROJECT_DIR_NAME%\%TMP_DIR%\%PROJECT_DIR_NAME%\src\%PKG_MSGS%\ %ROOTWS%\%PROJECT_DIR_NAME%\%SRC_DIR%\%PKG_MSGS%\ /E
CD %ROOTWS%\%PROJECT_DIR_NAME%
catkin_make
CD %ROOTWS%\%PROJECT_DIR_NAME%\%SRC_DIR%
catkin_create_pkg %PKG_NODES% roscpp %PKG_MSGS%
rmdir /S /Q %PKG_NODES%
xcopy %ROOTWS%\%PROJECT_DIR_NAME%\%TMP_DIR%\%PROJECT_DIR_NAME%\src\%PKG_NODES%\ %ROOTWS%\%PROJECT_DIR_NAME%\%SRC_DIR%\%PKG_NODES%\ /E
CD %ROOTWS%\%PROJECT_DIR_NAME%
catkin_make
rmdir /S /Q %TMP_DIR%

SET HMDRIVE=
SET ROOTWS=
SET PROJECT_DIR_NAME=
SET TMP_DIR=
SET SRC_DIR=
SET PKG_MSGS=
SET PKG_NODES=

exit